name: Pixel Value, soon be Opened
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "Pixel Value official site"
      links:
        - intro
        - vision
        - services
        - contacts


url: "http://pixelvalue.io"
og_image: "/assets/og_image.png"
